MODULE_FLAV := dbg
MODULE_CWARNS := all error
MODULE_CDEFS := PROJECT_DEF=1
MODULE_PROJECT_INCLUDE_DIRS := include
MODULE_ABS_INCLUDE_DIRS := /tmp
MODULE_PROJECT_LIB_DIRS := lib/$(MODULE_FLAV)

MY_PROJECT_LIB_ARTIFACT_DIR := lib/$(MODULE_FLAV)
