MODULE_PRE_SUB_MODULES := dynlib staticlib nobin multi-lang
MODULE_SUB_MODULES := prog multi-lang2
MODULE_POST_SUB_MODULES := prog2 prog-nobin prog-nobin-extern

staticlib: dynlib
multy-lang2: prog

include ../../module.inc.mk
