include ../config.mk

MODULE_NAME := invocation_shared
MODULE_BIN_TYPE := shared
MODULE_SRCS := invocation_shared.c
MODULE_ARTIFACT_DIR := $(TEST_PROJECT_LIB_DIR)
MODULE_VERBOSE := 0

include ../../../module.inc.mk

