MODULE_FLAV ?= dbg

TEST_PROJECT_ROOT_DIR := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
TEST_PROJECT_LIB_DIR := $(TEST_PROJECT_ROOT_DIR)lib/$(MODULE_FLAV)
TEST_PROJECT_INCLUDE_DIR := $(TEST_PROJECT_ROOT_DIR)include

MODULE_INCLUDE_DIRS := $(TEST_PROJECT_INCLUDE_DIR)
MODULE_LIB_DIRS := $(TEST_PROJECT_LIB_DIR)

