include ../config.mk

MODULE_NAME := static
MODULE_BIN_TYPE := static
MODULE_OBJS := static.c more_static/more_static.c
MODULE_ARTIFACT_DIR := $(MY_PROJECT_LIB_ARTIFACT_DIR)
MODULE_ARTIFACT_DIR_REL := 1

include ../../../module.inc.mk

