include ../config.mk

MODULE_NAME := invocation_shared
MODULE_BIN_TYPE := shared
MODULE_SRCS := invocation_shared.c
MODULE_ARTIFACT_DIR := $(TEST_PROJECT_LIB_DIR)
MODULE_VERBOSE := 0

TOP_LEVEL=$(shell git rev-parse --show-toplevel)
include $(TOP_LEVEL)/module.inc.mk
