include ../config.mk

MODULE_NAME := static
MODULE_BIN_TYPE := static
MODULE_SRCS := static.c more_static/more_static.c
MODULE_ARTIFACT_DIR := $(MY_PROJECT_LIB_ARTIFACT_DIR)
MODULE_ARTIFACT_DIR_REL := 1

PROJ_ROOT := $(shell git rev-parse --show-toplevel)
include $(PROJ_ROOT)/module.inc.mk
