include ../config.mk

MODULE_SRCS := main.cpp cfile.c cppfile.c++
MODULE_LANG := cpp
MODULE_C_SUFFIXES := c
MODULE_CXX_SUFFIXES := cpp c++

PROJ_ROOT := $(shell git rev-parse --show-toplevel)
include $(PROJ_ROOT)/module.inc.mk
